### ISSUE TITLE
validate Archimedian spiral Jacobian + incorporate aspect ratio parameter

### ISSUE THREAD

**Issue by corybrunson** [corybrunson/tdaunif#15]
While working on #11 i got a discrepancy between my own Jacobian calculations and those in the current implementation. Let's validate the Jacobian when we return to the project, and while we're at it possibly include an aspect ratio parameter (for vertical versus horizontal dimensions).

**Comment by 20demkowiczbr** [comment]
Sorry for taking so long to get to this. My recalculation of the Jacobian yielded `sqrt(1+theta^2)`. Does that match your calculation?

**Comment by corybrunson** [comment]
Yes, that sounds right!

By the way, since i don't think we've written it down anywhere, the reason to suggest an aspect ratio for some manifolds but not others is that it has an effect only when the the dimension of the manifold is lower than that of the ambient space. So, e.g., it's unnecessary for a planar triangle: Any linear transformation of a planar triangle sample within the plane is "area-preserving" in the sense that it effects the same change in density at every point. Since adjusting the aspect ratio is a linear transformation, one can generate the sample first and then change the aspect ratio, rather than vice-versa.
